# Generated by Django 5.0.2 on 2024-04-18 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_alter_user_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followers_count",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="following_count",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
