# Generated by Django 5.0.2 on 2024-04-19 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0008_alter_user_followers_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followers_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="following_count",
        ),
    ]
