# Generated by Django 5.0.2 on 2024-04-30 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0011_remove_post_likes_user_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="likes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_py",
                to="network.post",
            ),
        ),
    ]
