# Generated by Django 5.0.2 on 2024-04-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0014_alter_user_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="likes",
        ),
        migrations.AddField(
            model_name="user",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by", to="network.post"
            ),
        ),
    ]
