# Generated by Django 5.0.2 on 2024-05-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0015_remove_user_likes_user_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
